version: "3.7"
services:
  front:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    networks:
      - front
networks:
  front:
  backend:
  db:
volumes:
  db-data: